
stages:
  - build
  - publish-demo

build:
  image: node:16
  stage: build
  script:
    - export NODE_OPTIONS=--max-old-space-size=4096
    - npm install -g npm@7
    - npm install
    - npm run build
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules
      - packages/vis/lib
      - packages/dev-demo/lib
      - packages/vis-angular/storybook-static
      - packages/vis-react/storybook-static

pages:
  stage: publish-demo
  image: node:16
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - node_modules
      - packages/vis/lib
      - packages/dev-demo/lib
      - packages/vis-angular/storybook-static
      - packages/vis-react/storybook-static
  script:
    - export NODE_OPTIONS=--max-old-space-size=4096
    - npm install -g npm@7
    - npm install
    - npm run build
    - mv packages/dev-demo/lib/volterra-vis-examples public
    - cp public/index.html public/404.html
    - mv packages/vis-angular/storybook-static public/storybook-angular
    - mv packages/vis-react/storybook-static public/storybook-react
  artifacts:
    paths:
      - public
    expire_in: 6 hrs
  only:
    - main
