
stages:
  - build
  - publish-demo

build:
  image: volterrasystem/angular-e2e-testing:node14
  stage: build
  script:
    - npm install -g npm@7
    - npm install
    - npm run build
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules
      - packages/vis/lib
      - packages/dev-demo/lib
      - packages/vis-angular/storybook-static
      - packages/vis-react/storybook-static

pages:
  stage: publish-demo
  image: volterrasystem/angular-e2e-testing:node14
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - node_modules
      - packages/vis/lib
      - packages/dev-demo/lib
      - packages/vis-angular/storybook-static
      - packages/vis-rect/storybook-static
  script:
    - mv packages/dev-demo/lib/volterra-vis-examples public
    - cp public/index.html public/404.html
    - mv packages/vis-reacr/storybook-static public/storybook-react
    - mv packages/vis-angular/storybook-static public/storybook-angular
  artifacts:
    paths:
      - public
    expire_in: 6 hrs
  only:
    - main
