packages:
  - packages/ts
  - packages/angular
  - packages/react
  - packages/svelte
  - packages/vue
  - packages/solid
  - packages/shared
  - packages/dev
  - packages/website

catalog:
  vite: ^7.3.1