// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    'intro',
    'quick-start',
    {
      type: 'category',
      label: 'Component Reference',
      collapsible: false,
      link: { type: 'generated-index' },
      items: [
        {
          type: 'category',
          label: 'Containers',
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'containers' }],
        },
        {
          type: 'category',
          label: 'Components',
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'components' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'MCP Server',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'mcp' }],
    },
  ],
}

module.exports = sidebars
