export type DataRecord = {
  billions: number;
  name: string;
  category: string;
  year: number;
  sourceName: string;
  sourceUrl: string;
}

export const data: DataRecord[] = [
  {
    billions: 76.0,
    name: 'India',
    category: 'fighting',
    year: 2021.0,
    sourceName: 'SIPRI',
    sourceUrl: 'https://docs.google.com/spreadsheets/d/1ODLoOpc6RawyZNloyCtSSpmqvQqytqT86_mEWzLNxsg/edit#gid=673585979',
  },
  {
    billions: 68.0,
    name: 'UK',
    category: 'fighting',
    year: 2021.0,
    sourceName: 'SIPRI',
    sourceUrl: 'https://docs.google.com/spreadsheets/d/1ODLoOpc6RawyZNloyCtSSpmqvQqytqT86_mEWzLNxsg/edit#gid=673585979',
  },
  {
    billions: 65.0,
    name: 'Russia',
    category: 'fighting',
    year: 2021.0,
    sourceName: 'SIPRI',
    sourceUrl: 'https://docs.google.com/spreadsheets/d/1ODLoOpc6RawyZNloyCtSSpmqvQqytqT86_mEWzLNxsg/edit#gid=673585979',
  },
  {
    billions: 573.0,
    name: 'Walmart revenue',
    category: 'earning',
    year: 2022.0,
    sourceName: 'Walmart',
    sourceUrl: 'https://corporate.walmart.com/newsroom/2022/11/08/walmart-to-host-third-quarter-earnings-conference-call-nov-15-2022#:~:text=With%20fiscal%20year%202022%20revenue,corporate%20philanthropy%20and%20employment%20opportunity.',
  },
  {
    billions: 15.0,
    name: 'Amazon gross profit',
    category: 'earning',
    year: 2021.0,
    sourceName: 'Macrotrends',
    sourceUrl: 'https://www.macrotrends.net/stocks/charts/AMZN/amazon/gross-profit',
  },
  {
    billions: 33.0,
    name: 'Amazon net income',
    category: 'earning',
    year: 2021.0,
    sourceName: 'Macrotrends',
    sourceUrl: 'https://www.macrotrends.net/stocks/charts/AMZN/amazon/net-income#:~:text=Amazon%20annual%20net%20income%20for,a%2015.04%25%20increase%20from%202018.',
  },
  {
    billions: 394.0,
    name: 'Apple revenue',
    category: 'earning',
    year: 2022.0,
    sourceName: 'Statista',
    sourceUrl: "https://www.statista.com/statistics/265125/total-net-sales-of-apple-since-2004/#:~:text=Apple's%20total%20net%20sales%20amounted,in%20the%20last%20ten%20years.",
  },
  {
    billions: 100.0,
    name: 'Apple net income',
    category: 'earning',
    year: 2022.0,
    sourceName: 'Statista',
    sourceUrl: 'https://www.statista.com/statistics/267728/apples-net-income-since-2005/#:~:text=Apple%20reported%20net%20income%20of,dollars%20in%20that%20same%20year.',
  },
  {
    billions: 322.0,
    name: 'Donated to charity by Americans (per year)',
    category: 'giving',
    year: 2019.0,
    sourceName: 'Alysterling',
    sourceUrl: 'http://www.alysterling.com/documents/GUSA2012ExecutiveSummary.pdf',
  },
  {
    billions: 23.0,
    name: 'NASA',
    category: 'spending',
    year: 2021.0,
    sourceName: 'NASA',
    sourceUrl: "https://www.planetary.org/space-policy/nasas-fy-2021-budget#:~:text=NASA's%20budget%20for%20fiscal%20year,months%20into%20the%20fiscal%20year.",
  },
  {
    billions: 15000.0,
    name: 'Worldwide cost of financial crisis',
    category: 'losing',
    year: 2012.0,
    sourceName: 'Wall St Journal',
    sourceUrl: 'https://www.wsj.com/articles/BL-REB-17312',
  },
  {
    billions: 12500.0,
    name: 'Cost of COVID measures worldwide',
    category: 'losing',
    year: 2022.0,
    sourceName: 'Reuters / IMF',
    sourceUrl: 'https://www.reuters.com/business/imf-sees-cost-covid-pandemic-rising-beyond-125-trillion-estimate-2022-01-20/',
  },
  {
    billions: 327.0,
    name: 'OPEC revenue',
    category: 'earning',
    year: 2021.0,
    sourceName: 'Statista',
    sourceUrl: "https://www.statista.com/statistics/223241/opec-net-oil-export-revenue/#:~:text=This%20statistic%20represents%20OPEC's%20net,of%20the%20Petroleum%20Exporting%20Countries.",
  },
  {
    billions: 640.0,
    name: 'The War on Drugs (since 1971)',
    category: 'spending',
    year: 2019.0,
    sourceName: 'Human Rights Foundation',
    sourceUrl: 'https://hrf.org/wp-content/uploads/2019/05/WoD_Online-version-FINAL.pdf',
  },
  {
    billions: 87.0,
    name: 'Ebay goods',
    category: 'spending',
    year: 2021.0,
    sourceName: 'Statista',
    sourceUrl: 'https://www.statista.com/statistics/242276/ebays-fixed-price-trading-as-share-of-total-gross-merchandise-volume/',
  },
  {
    billions: 10.0,
    name: 'Ebay net revenue',
    category: 'earning',
    year: 2021.0,
    sourceName: 'Statista',
    sourceUrl: 'https://www.statista.com/statistics/507881/ebays-annual-net-revenue/',
  },
  {
    billions: 169.0,
    name: 'Total foreign aid payments',
    category: 'giving',
    year: 2019.0,
    sourceName: 'Wikipedia',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_development_aid_country_donors',
  },
  {
    billions: 417.0,
    name: "Africa's foreign debt",
    category: 'owing',
    year: 2018.0,
    sourceName: 'Jubilee Debt Campaign',
    sourceUrl: 'https://jubileedebt.org.uk/wp/wp-content/uploads/2018/10/Who-is-Africa-debt-owed-to_10.18.pdf',
  },
  {
    billions: 100.0,
    name: "Africa's foreign debt",
    category: 'owing',
    year: 2018.0,
    sourceName: 'Jubilee Debt Campaign',
    sourceUrl: 'https://jubileedebt.org.uk/wp/wp-content/uploads/2018/10/Who-is-Africa-debt-owed-to_10.18.pdf',
  },
  {
    billions: 158.0,
    name: 'Bill Gates',
    category: 'accumulating',
    year: 2024.0,
    sourceName: 'Bloomberg',
    sourceUrl: 'https://www.bloomberg.com/billionaires/',
  },
  {
    billions: 437.0,
    name: 'Elon Musk net worth',
    category: 'accumulating',
    year: 2024.0,
    sourceName: 'Bloomberg',
    sourceUrl: 'https://www.bloomberg.com/billionaires/',
  },
  {
    billions: 243.0,
    name: 'Jeff Bezos',
    category: 'accumulating',
    year: 2024.0,
    sourceName: 'Bloomberg',
    sourceUrl: 'https://www.bloomberg.com/billionaires/',
  },
  {
    billions: 169.0,
    name: 'Bernard Arnault',
    category: 'accumulating',
    year: 2024.0,
    sourceName: 'Bloomberg',
    sourceUrl: 'https://www.bloomberg.com/billionaires/',
  },
  {
    billions: 214.0,
    name: 'Mark Zuckerberg',
    category: 'accumulating',
    year: 2024.0,
    sourceName: 'Bloomberg',
    sourceUrl: 'https://www.bloomberg.com/billionaires/',
  },
  {
    billions: 125.0,
    name: 'Save the Amazon',
    category: 'giving',
    year: 2018.0,
    sourceName: 'IFL Science',
    sourceUrl: 'https://www.iflscience.com/environment/saving-the-amazon-would-be-up-to-50-times-cheaper-than-the-cost-of-losing-it/',
  },
  {
    billions: 5800.0,
    name: 'Iraq & Afghanistan wars total cost',
    category: 'fighting',
    year: 2019.0,
    sourceName: 'Brown University',
    sourceUrl: 'https://watson.brown.edu/costsofwar/figures/2021/BudgetaryCosts',
  },
  {
    billions: 82.0,
    name: 'Alternative medicine',
    category: 'spending',
    year: 2020.0,
    sourceName: 'Grand View Research',
    sourceUrl: 'https://www.grandviewresearch.com/industry-analysis/complementary-alternative-medicine-market',
  },
  {
    billions: 195.0,
    name: 'Video games market',
    category: 'spending',
    year: 2021.0,
    sourceName: 'Grand View Research',
    sourceUrl: 'https://www.grandviewresearch.com/industry-analysis/video-game-market#:~:text=The%20global%20video%20game%20market,12.9%25%20from%202020%20to%202027.',
  },
  {
    billions: 15.0,
    name: 'Porn',
    category: 'spending',
    year: 2018.0,
    sourceName: 'The Guardian',
    sourceUrl: 'https://www.theguardian.com/commentisfree/2018/dec/30/internet-porn-says-more-about-ourselves-than-technology#:~:text=Current%20revenue%20estimates%20for%20the,words%2C%20online%20porn%20is%20huge.',
  },
  {
    billions: 1250.0,
    name: 'Global pharmaceutical market',
    category: 'earning',
    year: 2021.0,
    sourceName: 'Global News Wire',
    sourceUrl: 'https://www.globenewswire.com/en/news-release/2021/03/31/2202135/28124/en/Global-Pharmaceuticals-Market-Report-2021-Market-is-Expected-to-Grow-from-1228-45-Billion-in-2020-to-1250-24-Billion-in-2021-Long-term-Forecast-to-2025-2030.html/#:~:text=The%20global%20pharmaceuticals%20market%20is,(CAGR)%20of%201.8%25.',
  },
  {
    billions: 27.0,
    name: 'UN',
    category: 'spending',
    year: 2022.0,
    sourceName: 'United Nations',
    sourceUrl: 'https://betterworldcampaign.org/resources/briefing-book-2022/united-nations-budget',
  },
  {
    billions: 1700.0,
    name: 'US student debt',
    category: 'owing',
    year: 2020.0,
    sourceName: 'CNBC',
    sourceUrl: 'https://www.cnbc.com/2020/12/22/us-student-debt-has-increased-by-more-than-100percent-over-past-10-years.html#:~:text=The%20Federal%20Reserve%20estimates%20that,when%20compared%20to%20decades%20prior.',
  },
  {
    billions: 13.0,
    name: 'Legal cannabis market',
    category: 'spending',
    year: 2021.0,
    sourceName: 'Grand View Research',
    sourceUrl: 'https://www.grandviewresearch.com/industry-analysis/legal-marijuana-market',
  },
  {
    billions: 6.8,
    name: 'WHO',
    category: 'giving',
    year: 2024.0,
    sourceName: 'WHO',
    sourceUrl: 'https://www.who.int/about/accountability/budget',
  },
  {
    billions: 233.0,
    name: 'AI global market value',
    category: 'spending',
    year: 2024.0,
    sourceName: 'Forbes',
    sourceUrl: 'https://www.fortunebusinessinsights.com/industry-reports/artificial-intelligence-market-100114',
  },
].sort((a, b) => b.billions - a.billions)
