// Types
export type NodeDatum = {
  id: string;
  label: string;
  group: string;
  continent: string;
}

export type LinkDatum = {
  id: string;
  source: string;
  target: string;
  airline: {
    name: string;
    country: string;
    continent: string;
    countryCode: string;
  };
}

// Styles
export const styleUrl = 'https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css'
export const getFlag = (cc: string): string => `
  <div style="width: 24px; display:inline-block">
    <span class="fi fi-${cc}"/>
  </div>`

// Data
const nodes: NodeDatum[] = [
  {
    id: 'DJ',
    label: 'Djibouti',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'AE',
    label: 'United Arab Emirates',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'SA',
    label: 'Saudi Arabia',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'SO',
    label: 'Somalia',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'KE',
    label: 'Kenya',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'CA',
    label: 'Canada',
    continent: 'North America',
    group: 'B',
  },
  {
    id: 'CL',
    label: 'Chile',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'TH',
    label: 'Thailand',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'KR',
    label: 'South Korea',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'PH',
    label: 'Philippines',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'JP',
    label: 'Japan',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'GU',
    label: 'Guam',
    continent: 'Oceania',
    group: 'A',
  },
  {
    id: 'HK',
    label: 'Hong Kong',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'CN',
    label: 'China',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'MM',
    label: 'Burma',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'TD',
    label: 'Chad',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'IN',
    label: 'India',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'GE',
    label: 'Georgia',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'IL',
    label: 'Israel',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'RU',
    label: 'Russia',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'AU',
    label: 'Australia',
    continent: 'Oceania',
    group: 'A',
  },
  {
    id: 'NZ',
    label: 'New Zealand',
    continent: 'Oceania',
    group: 'A',
  },
  {
    id: 'US',
    label: 'United States',
    continent: 'North America',
    group: 'B',
  },
  {
    id: 'MY',
    label: 'Malaysia',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'MX',
    label: 'Mexico',
    continent: 'North America',
    group: 'B',
  },
  {
    id: 'BS',
    label: 'Bahamas',
    continent: 'North America',
    group: 'B',
  },
  {
    id: 'SG',
    label: 'Singapore',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'TW',
    label: 'Taiwan',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'CO',
    label: 'Colombia',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'VE',
    label: 'Venezuela',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'CU',
    label: 'Cuba',
    continent: 'North America',
    group: 'B',
  },
  {
    id: 'EC',
    label: 'Ecuador',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'AR',
    label: 'Argentina',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'PY',
    label: 'Paraguay',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'BR',
    label: 'Brazil',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'UY',
    label: 'Uruguay',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'PE',
    label: 'Peru',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'BO',
    label: 'Bolivia',
    continent: 'South America',
    group: 'B',
  },
  {
    id: 'NL',
    label: 'Netherlands',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'SE',
    label: 'Sweden',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'NO',
    label: 'Norway',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'DK',
    label: 'Denmark',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'GB',
    label: 'United Kingdom',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'DE',
    label: 'Germany',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'FI',
    label: 'Finland',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'IT',
    label: 'Italy',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'AL',
    label: 'Albania',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'KP',
    label: 'North Korea',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'KH',
    label: 'Cambodia',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'VN',
    label: 'Vietnam',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'PG',
    label: 'Papua New Guinea',
    continent: 'Oceania',
    group: 'A',
  },
  {
    id: 'TR',
    label: 'Turkey',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'ID',
    label: 'Indonesia',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'LK',
    label: 'Sri Lanka',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'ES',
    label: 'Spain',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'UA',
    label: 'Ukraine',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'MD',
    label: 'Moldova',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'SN',
    label: 'Senegal',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'EG',
    label: 'Egypt',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'AZ',
    label: 'Azerbaijan',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'SD',
    label: 'Sudan',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'GR',
    label: 'Greece',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'HU',
    label: 'Hungary',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'FR',
    label: 'France',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'CH',
    label: 'Switzerland',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'PT',
    label: 'Portugal',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'RO',
    label: 'Romania',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'CZ',
    label: 'Czech Republic',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'LV',
    label: 'Latvia',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'AT',
    label: 'Austria',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'PL',
    label: 'Poland',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'CG',
    label: 'Congo (Brazzaville)',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'CD',
    label: 'Congo (Kinshasa)',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'YT',
    label: 'Mayotte',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'KM',
    label: 'Comoros',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'ZM',
    label: 'Zambia',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'MW',
    label: 'Malawi',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'PA',
    label: 'Panama',
    continent: 'North America',
    group: 'B',
  },
  {
    id: 'CR',
    label: 'Costa Rica',
    continent: 'North America',
    group: 'B',
  },
  {
    id: 'MT',
    label: 'Malta',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'BJ',
    label: 'Benin',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'CM',
    label: 'Cameroon',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'LA',
    label: 'Laos',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'MV',
    label: 'Maldives',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'BD',
    label: 'Bangladesh',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'NP',
    label: 'Nepal',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'MN',
    label: 'Mongolia',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'PK',
    label: 'Pakistan',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'BH',
    label: 'Bahrain',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'OM',
    label: 'Oman',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'IR',
    label: 'Iran',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'CY',
    label: 'Cyprus',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'BY',
    label: 'Belarus',
    continent: 'Europe',
    group: 'C',
  },
  {
    id: 'SB',
    label: 'Solomon Islands',
    continent: 'Oceania',
    group: 'A',
  },
  {
    id: 'FJ',
    label: 'Fiji',
    continent: 'Oceania',
    group: 'A',
  },
  {
    id: 'CI',
    label: "Cote d'Ivoire",
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'NG',
    label: 'Nigeria',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'GA',
    label: 'Gabon',
    continent: 'Africa',
    group: 'A',
  },
  {
    id: 'JO',
    label: 'Jordan',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'AF',
    label: 'Afghanistan',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'TJ',
    label: 'Tajikistan',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'KZ',
    label: 'Kazakhstan',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'KN',
    label: 'Saint Kitts and Nevis',
    continent: 'North America',
    group: 'B',
  },
  {
    id: 'KG',
    label: 'Kyrgyzstan',
    continent: 'Asia',
    group: 'C',
  },
  {
    id: 'ET',
    label: 'Ethiopia',
    continent: 'Africa',
    group: 'A',
  },
]

const links: LinkDatum[] = [{
  id: 'DJ-AE-3J',
  source: 'DJ',
  target: 'AE',
  airline: {
    name: 'Zip',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'DJ-SA-3J',
  source: 'DJ',
  target: 'SA',
  airline: {
    name: 'Zip',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'DJ-SO-3J',
  source: 'DJ',
  target: 'SO',
  airline: {
    name: 'Zip',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'SO-KE-3J',
  source: 'SO',
  target: 'KE',
  airline: {
    name: 'Zip',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'KE-SO-3J',
  source: 'KE',
  target: 'SO',
  airline: {
    name: 'Zip',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'CA-CA-4N',
  source: 'CA',
  target: 'CA',
  airline: {
    name: 'Air North Charter - Canada',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'CL-CL-5P',
  source: 'CL',
  target: 'CL',
  airline: {
    name: 'Pal airlines',
    country: 'Chile',
    countryCode: 'cl',
    continent: 'South America',
  },
},
{
  id: 'CA-CA-7F',
  source: 'CA',
  target: 'CA',
  airline: {
    name: 'First Air',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'CN-CN-8L',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'Cargo Plus Aviation',
    country: 'United Arab Emirates',
    countryCode: 'ae',
    continent: 'Asia',
  },
},
{
  id: 'KR-MM-8M',
  source: 'KR',
  target: 'MM',
  airline: {
    name: 'Maxair',
    country: 'Sweden',
    countryCode: 'se',
    continent: 'Europe',
  },
},
{
  id: 'MM-KR-8M',
  source: 'MM',
  target: 'KR',
  airline: {
    name: 'Maxair',
    country: 'Sweden',
    countryCode: 'se',
    continent: 'Europe',
  },
},
{
  id: 'SA-TD-9D',
  source: 'SA',
  target: 'TD',
  airline: {
    name: 'Air Carnival',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'IN-JP-9W',
  source: 'IN',
  target: 'JP',
  airline: {
    name: 'Jet Airways',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'JP-IN-9W',
  source: 'JP',
  target: 'IN',
  airline: {
    name: 'Jet Airways',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'GE-IL-A9',
  source: 'GE',
  target: 'IL',
  airline: {
    name: 'Georgian Airways',
    country: 'Georgia',
    countryCode: 'ge',
    continent: 'Asia',
  },
},
{
  id: 'GE-RU-A9',
  source: 'GE',
  target: 'RU',
  airline: {
    name: 'Georgian Airways',
    country: 'Georgia',
    countryCode: 'ge',
    continent: 'Asia',
  },
},
{
  id: 'IL-GE-A9',
  source: 'IL',
  target: 'GE',
  airline: {
    name: 'Georgian Airways',
    country: 'Georgia',
    countryCode: 'ge',
    continent: 'Asia',
  },
},
{
  id: 'RU-GE-A9',
  source: 'RU',
  target: 'GE',
  airline: {
    name: 'Georgian Airways',
    country: 'Georgia',
    countryCode: 'ge',
    continent: 'Asia',
  },
},
{
  id: 'AU-AU-AA',
  source: 'AU',
  target: 'AU',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'NZ-AU-AA',
  source: 'NZ',
  target: 'AU',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'US-US-AA',
  source: 'US',
  target: 'US',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'TH-MY-AA',
  source: 'TH',
  target: 'MY',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'AU-NZ-AA',
  source: 'AU',
  target: 'NZ',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'US-MX-AA',
  source: 'US',
  target: 'MX',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'US-BS-AA',
  source: 'US',
  target: 'BS',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'MX-US-AA',
  source: 'MX',
  target: 'US',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'JP-JP-AA',
  source: 'JP',
  target: 'JP',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'KR-JP-AA',
  source: 'KR',
  target: 'JP',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'US-CA-AA',
  source: 'US',
  target: 'CA',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'MY-TH-AA',
  source: 'MY',
  target: 'TH',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'MY-MY-AA',
  source: 'MY',
  target: 'MY',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'MY-SG-AA',
  source: 'MY',
  target: 'SG',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'BS-US-AA',
  source: 'BS',
  target: 'US',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'JP-KR-AA',
  source: 'JP',
  target: 'KR',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'JP-TW-AA',
  source: 'JP',
  target: 'TW',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'SG-MY-AA',
  source: 'SG',
  target: 'MY',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'TW-JP-AA',
  source: 'TW',
  target: 'JP',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'CA-US-AA',
  source: 'CA',
  target: 'US',
  airline: {
    name: 'American Airlines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'US-CA-AC',
  source: 'US',
  target: 'CA',
  airline: {
    name: 'Air Canada',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'CA-US-AC',
  source: 'CA',
  target: 'US',
  airline: {
    name: 'Air Canada',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'MX-MX-AM',
  source: 'MX',
  target: 'MX',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'CO-MX-AM',
  source: 'CO',
  target: 'MX',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'VE-MX-AM',
  source: 'VE',
  target: 'MX',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'MX-CU-AM',
  source: 'MX',
  target: 'CU',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'MX-US-AM',
  source: 'MX',
  target: 'US',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'CU-MX-AM',
  source: 'CU',
  target: 'MX',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'US-MX-AM',
  source: 'US',
  target: 'MX',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'MX-CO-AM',
  source: 'MX',
  target: 'CO',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'MX-VE-AM',
  source: 'MX',
  target: 'VE',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'MX-EC-AM',
  source: 'MX',
  target: 'EC',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'EC-MX-AM',
  source: 'EC',
  target: 'MX',
  airline: {
    name: 'AeroMéxico',
    country: 'Mexico',
    countryCode: 'mx',
    continent: 'North America',
  },
},
{
  id: 'AR-PY-AR',
  source: 'AR',
  target: 'PY',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'AR-AR-AR',
  source: 'AR',
  target: 'AR',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'AR-BR-AR',
  source: 'AR',
  target: 'BR',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'AR-UY-AR',
  source: 'AR',
  target: 'UY',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'AR-CL-AR',
  source: 'AR',
  target: 'CL',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'PY-AR-AR',
  source: 'PY',
  target: 'AR',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'BR-AR-AR',
  source: 'BR',
  target: 'AR',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'AR-PE-AR',
  source: 'AR',
  target: 'PE',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'AR-BO-AR',
  source: 'AR',
  target: 'BO',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'PE-AR-AR',
  source: 'PE',
  target: 'AR',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'UY-AR-AR',
  source: 'UY',
  target: 'AR',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'CL-AR-AR',
  source: 'CL',
  target: 'AR',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'BO-AR-AR',
  source: 'BO',
  target: 'AR',
  airline: {
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    countryCode: 'ar',
    continent: 'South America',
  },
},
{
  id: 'NL-SE-AZ',
  source: 'NL',
  target: 'SE',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'NL-NO-AZ',
  source: 'NL',
  target: 'NO',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'NL-DK-AZ',
  source: 'NL',
  target: 'DK',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'NL-GB-AZ',
  source: 'NL',
  target: 'GB',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'NL-DE-AZ',
  source: 'NL',
  target: 'DE',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'NL-FI-AZ',
  source: 'NL',
  target: 'FI',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'NL-IT-AZ',
  source: 'NL',
  target: 'IT',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'SE-NL-AZ',
  source: 'SE',
  target: 'NL',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'NO-NL-AZ',
  source: 'NO',
  target: 'NL',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'DK-NL-AZ',
  source: 'DK',
  target: 'NL',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'GB-NL-AZ',
  source: 'GB',
  target: 'NL',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'DE-NL-AZ',
  source: 'DE',
  target: 'NL',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'FI-NL-AZ',
  source: 'FI',
  target: 'NL',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'MX-US-AZ',
  source: 'MX',
  target: 'US',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'US-MX-AZ',
  source: 'US',
  target: 'MX',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-NL-AZ',
  source: 'IT',
  target: 'NL',
  airline: {
    name: 'Alitalia',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'GB-IT-BA',
  source: 'GB',
  target: 'IT',
  airline: {
    name: 'British Airways',
    country: 'United Kingdom',
    countryCode: 'gb',
    continent: 'Europe',
  },
},
{
  id: 'IT-GB-BA',
  source: 'IT',
  target: 'GB',
  airline: {
    name: 'British Airways',
    country: 'United Kingdom',
    countryCode: 'gb',
    continent: 'Europe',
  },
},
{
  id: 'JP-JP-BC',
  source: 'JP',
  target: 'JP',
  airline: {
    name: 'Skymark Airlines',
    country: 'Japan',
    countryCode: 'jp',
    continent: 'Asia',
  },
},
{
  id: 'IT-AL-BV',
  source: 'IT',
  target: 'AL',
  airline: {
    name: 'Blue Panorama Airlines',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-IT-BV',
  source: 'IT',
  target: 'IT',
  airline: {
    name: 'Blue Panorama Airlines',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'RU-IT-BV',
  source: 'RU',
  target: 'IT',
  airline: {
    name: 'Blue Panorama Airlines',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-RU-BV',
  source: 'IT',
  target: 'RU',
  airline: {
    name: 'Blue Panorama Airlines',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'AL-IT-BV',
  source: 'AL',
  target: 'IT',
  airline: {
    name: 'Blue Panorama Airlines',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'CN-CN-CA',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-HK-CA',
  source: 'CN',
  target: 'HK',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'KP-CN-CA',
  source: 'KP',
  target: 'CN',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-JP-CA',
  source: 'CN',
  target: 'JP',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'HK-CN-CA',
  source: 'HK',
  target: 'CN',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-RU-CA',
  source: 'CN',
  target: 'RU',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'RU-CN-CA',
  source: 'RU',
  target: 'CN',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'JP-CN-CA',
  source: 'JP',
  target: 'CN',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-KP-CA',
  source: 'CN',
  target: 'KP',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-KH-CA',
  source: 'CN',
  target: 'KH',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-VN-CA',
  source: 'CN',
  target: 'VN',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'KH-CN-CA',
  source: 'KH',
  target: 'CN',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'VN-CN-CA',
  source: 'VN',
  target: 'CN',
  airline: {
    name: 'Air China',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'AU-PG-CG',
  source: 'AU',
  target: 'PG',
  airline: {
    name: 'Airlines PNG',
    country: 'Papua New Guinea',
    countryCode: 'pg',
    continent: 'Oceania',
  },
},
{
  id: 'PG-AU-CG',
  source: 'PG',
  target: 'AU',
  airline: {
    name: 'Airlines PNG',
    country: 'Papua New Guinea',
    countryCode: 'pg',
    continent: 'Oceania',
  },
},
{
  id: 'NL-GB-CI',
  source: 'NL',
  target: 'GB',
  airline: {
    name: 'China Airlines',
    country: 'Taiwan',
    countryCode: 'tw',
    continent: 'Asia',
  },
},
{
  id: 'GB-NL-CI',
  source: 'GB',
  target: 'NL',
  airline: {
    name: 'China Airlines',
    country: 'Taiwan',
    countryCode: 'tw',
    continent: 'Asia',
  },
},
{
  id: 'CN-CN-CZ',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'China Southern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'MX-US-DL',
  source: 'MX',
  target: 'US',
  airline: {
    name: 'Delta Air Lines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'DE-NL-DL',
  source: 'DE',
  target: 'NL',
  airline: {
    name: 'Delta Air Lines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'US-MX-DL',
  source: 'US',
  target: 'MX',
  airline: {
    name: 'Delta Air Lines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'MX-MX-DL',
  source: 'MX',
  target: 'MX',
  airline: {
    name: 'Delta Air Lines',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'AE-IN-EY',
  source: 'AE',
  target: 'IN',
  airline: {
    name: 'Etihad Airways',
    country: 'United Arab Emirates',
    countryCode: 'ae',
    continent: 'Asia',
  },
},
{
  id: 'AE-AE-EY',
  source: 'AE',
  target: 'AE',
  airline: {
    name: 'Etihad Airways',
    country: 'United Arab Emirates',
    countryCode: 'ae',
    continent: 'Asia',
  },
},
{
  id: 'AE-TR-EY',
  source: 'AE',
  target: 'TR',
  airline: {
    name: 'Etihad Airways',
    country: 'United Arab Emirates',
    countryCode: 'ae',
    continent: 'Asia',
  },
},
{
  id: 'IN-AE-EY',
  source: 'IN',
  target: 'AE',
  airline: {
    name: 'Etihad Airways',
    country: 'United Arab Emirates',
    countryCode: 'ae',
    continent: 'Asia',
  },
},
{
  id: 'ID-AU-EY',
  source: 'ID',
  target: 'AU',
  airline: {
    name: 'Etihad Airways',
    country: 'United Arab Emirates',
    countryCode: 'ae',
    continent: 'Asia',
  },
},
{
  id: 'LK-AE-EY',
  source: 'LK',
  target: 'AE',
  airline: {
    name: 'Etihad Airways',
    country: 'United Arab Emirates',
    countryCode: 'ae',
    continent: 'Asia',
  },
},
{
  id: 'TR-AE-EY',
  source: 'TR',
  target: 'AE',
  airline: {
    name: 'Etihad Airways',
    country: 'United Arab Emirates',
    countryCode: 'ae',
    continent: 'Asia',
  },
},
{
  id: 'AU-ID-EY',
  source: 'AU',
  target: 'ID',
  airline: {
    name: 'Etihad Airways',
    country: 'United Arab Emirates',
    countryCode: 'ae',
    continent: 'Asia',
  },
},
{
  id: 'CN-CN-FM',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'Shanghai Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'KR-CN-FM',
  source: 'KR',
  target: 'CN',
  airline: {
    name: 'Shanghai Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-KR-FM',
  source: 'CN',
  target: 'KR',
  airline: {
    name: 'Shanghai Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-CN-HU',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'Hainan Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'JP-RU-HZ',
  source: 'JP',
  target: 'RU',
  airline: {
    name: 'Sat Airlines',
    country: 'Kazakhstan',
    countryCode: 'kz',
    continent: 'Asia',
  },
},
{
  id: 'KR-RU-HZ',
  source: 'KR',
  target: 'RU',
  airline: {
    name: 'Sat Airlines',
    country: 'Kazakhstan',
    countryCode: 'kz',
    continent: 'Asia',
  },
},
{
  id: 'RU-CN-HZ',
  source: 'RU',
  target: 'CN',
  airline: {
    name: 'Sat Airlines',
    country: 'Kazakhstan',
    countryCode: 'kz',
    continent: 'Asia',
  },
},
{
  id: 'RU-RU-HZ',
  source: 'RU',
  target: 'RU',
  airline: {
    name: 'Sat Airlines',
    country: 'Kazakhstan',
    countryCode: 'kz',
    continent: 'Asia',
  },
},
{
  id: 'RU-JP-HZ',
  source: 'RU',
  target: 'JP',
  airline: {
    name: 'Sat Airlines',
    country: 'Kazakhstan',
    countryCode: 'kz',
    continent: 'Asia',
  },
},
{
  id: 'IT-IT-I9',
  source: 'IT',
  target: 'IT',
  airline: {
    name: 'Air Italy',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'ES-UA-IB',
  source: 'ES',
  target: 'UA',
  airline: {
    name: 'Iberia Airlines',
    country: 'Spain',
    countryCode: 'es',
    continent: 'Europe',
  },
},
{
  id: 'UA-ES-IB',
  source: 'UA',
  target: 'ES',
  airline: {
    name: 'Iberia Airlines',
    country: 'Spain',
    countryCode: 'es',
    continent: 'Europe',
  },
},
{
  id: 'IT-IT-IG',
  source: 'IT',
  target: 'IT',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-MD-IG',
  source: 'IT',
  target: 'MD',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'SN-IT-IG',
  source: 'SN',
  target: 'IT',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'ES-IT-IG',
  source: 'ES',
  target: 'IT',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'UA-IT-IG',
  source: 'UA',
  target: 'IT',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'MD-IT-IG',
  source: 'MD',
  target: 'IT',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'GB-IT-IG',
  source: 'GB',
  target: 'IT',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-SN-IG',
  source: 'IT',
  target: 'SN',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-ES-IG',
  source: 'IT',
  target: 'ES',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-EG-IG',
  source: 'IT',
  target: 'EG',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-IL-IG',
  source: 'IT',
  target: 'IL',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-UA-IG',
  source: 'IT',
  target: 'UA',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IT-GB-IG',
  source: 'IT',
  target: 'GB',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'IL-IT-IG',
  source: 'IL',
  target: 'IT',
  airline: {
    name: 'Meridiana',
    country: 'Italy',
    countryCode: 'it',
    continent: 'Europe',
  },
},
{
  id: 'ID-ID-IL',
  source: 'ID',
  target: 'ID',
  airline: {
    name: 'Illinois Airways',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'AZ-UA-J2',
  source: 'AZ',
  target: 'UA',
  airline: {
    name: 'Azerbaijan Airlines',
    country: 'Azerbaijan',
    countryCode: 'az',
    continent: 'Asia',
  },
},
{
  id: 'UA-AZ-J2',
  source: 'UA',
  target: 'AZ',
  airline: {
    name: 'Azerbaijan Airlines',
    country: 'Azerbaijan',
    countryCode: 'az',
    continent: 'Asia',
  },
},
{
  id: 'SD-SD-J4',
  source: 'SD',
  target: 'SD',
  airline: {
    name: 'ALAK',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'SO-DJ-JU',
  source: 'SO',
  target: 'DJ',
  airline: {
    name: 'Air Serbia',
    country: 'Russia',
    countryCode: 'rs',
    continent: 'Europe',
  },
},
{
  id: 'AE-SO-JU',
  source: 'AE',
  target: 'SO',
  airline: {
    name: 'Air Serbia',
    country: 'Russia',
    countryCode: 'rs',
    continent: 'Europe',
  },
},
{
  id: 'SO-SO-JU',
  source: 'SO',
  target: 'SO',
  airline: {
    name: 'Air Serbia',
    country: 'Russia',
    countryCode: 'rs',
    continent: 'Europe',
  },
},
{
  id: 'DJ-AE-JU',
  source: 'DJ',
  target: 'AE',
  airline: {
    name: 'Air Serbia',
    country: 'Russia',
    countryCode: 'rs',
    continent: 'Europe',
  },
},
{
  id: 'DJ-SO-JU',
  source: 'DJ',
  target: 'SO',
  airline: {
    name: 'Air Serbia',
    country: 'Russia',
    countryCode: 'rs',
    continent: 'Europe',
  },
},
{
  id: 'GB-NL-KL',
  source: 'GB',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'CN-CN-KL',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-GB-KL',
  source: 'NL',
  target: 'GB',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-SE-KL',
  source: 'NL',
  target: 'SE',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-GR-KL',
  source: 'NL',
  target: 'GR',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-ES-KL',
  source: 'NL',
  target: 'ES',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-NO-KL',
  source: 'NL',
  target: 'NO',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-DK-KL',
  source: 'NL',
  target: 'DK',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-HU-KL',
  source: 'NL',
  target: 'HU',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-FR-KL',
  source: 'NL',
  target: 'FR',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-IT-KL',
  source: 'NL',
  target: 'IT',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-CH-KL',
  source: 'NL',
  target: 'CH',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-DE-KL',
  source: 'NL',
  target: 'DE',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-FI-KL',
  source: 'NL',
  target: 'FI',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-TR-KL',
  source: 'NL',
  target: 'TR',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-UA-KL',
  source: 'NL',
  target: 'UA',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-RU-KL',
  source: 'NL',
  target: 'RU',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-PT-KL',
  source: 'NL',
  target: 'PT',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-RO-KL',
  source: 'NL',
  target: 'RO',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-CZ-KL',
  source: 'NL',
  target: 'CZ',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-LV-KL',
  source: 'NL',
  target: 'LV',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-GE-KL',
  source: 'NL',
  target: 'GE',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-IL-KL',
  source: 'NL',
  target: 'IL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-AT-KL',
  source: 'NL',
  target: 'AT',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NL-PL-KL',
  source: 'NL',
  target: 'PL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'SE-NL-KL',
  source: 'SE',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'GR-NL-KL',
  source: 'GR',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'ES-NL-KL',
  source: 'ES',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'BR-BR-KL',
  source: 'BR',
  target: 'BR',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'NO-NL-KL',
  source: 'NO',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'DK-NL-KL',
  source: 'DK',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'HU-NL-KL',
  source: 'HU',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'CG-CD-KL',
  source: 'CG',
  target: 'CD',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'FR-NL-KL',
  source: 'FR',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'YT-KM-KL',
  source: 'YT',
  target: 'KM',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'AR-AR-KL',
  source: 'AR',
  target: 'AR',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'IT-NL-KL',
  source: 'IT',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'CD-CG-KL',
  source: 'CD',
  target: 'CG',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'CH-NL-KL',
  source: 'CH',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'DE-NL-KL',
  source: 'DE',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'FI-NL-KL',
  source: 'FI',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'TR-NL-KL',
  source: 'TR',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'US-US-KL',
  source: 'US',
  target: 'US',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'UA-NL-KL',
  source: 'UA',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'TW-SG-KL',
  source: 'TW',
  target: 'SG',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'MY-MY-KL',
  source: 'MY',
  target: 'MY',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'RU-NL-KL',
  source: 'RU',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'PT-NL-KL',
  source: 'PT',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'ZM-MW-KL',
  source: 'ZM',
  target: 'MW',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'MX-MX-KL',
  source: 'MX',
  target: 'MX',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'KE-CG-KL',
  source: 'KE',
  target: 'CG',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'KE-YT-KL',
  source: 'KE',
  target: 'YT',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'KE-CD-KL',
  source: 'KE',
  target: 'CD',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'KE-ZM-KL',
  source: 'KE',
  target: 'ZM',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'RO-NL-KL',
  source: 'RO',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'CZ-NL-KL',
  source: 'CZ',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'PA-CR-KL',
  source: 'PA',
  target: 'CR',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'LV-NL-KL',
  source: 'LV',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'GE-NL-KL',
  source: 'GE',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'IL-NL-KL',
  source: 'IL',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'AT-NL-KL',
  source: 'AT',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'PL-NL-KL',
  source: 'PL',
  target: 'NL',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'CA-CA-KL',
  source: 'CA',
  target: 'CA',
  airline: {
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    countryCode: 'nl',
    continent: 'Europe',
  },
},
{
  id: 'TR-MT-KM',
  source: 'TR',
  target: 'MT',
  airline: {
    name: 'Air Malta',
    country: 'Malta',
    countryCode: 'mt',
    continent: 'Europe',
  },
},
{
  id: 'MT-TR-KM',
  source: 'MT',
  target: 'TR',
  airline: {
    name: 'Air Malta',
    country: 'Malta',
    countryCode: 'mt',
    continent: 'Europe',
  },
},
{
  id: 'CN-CN-KN',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'China United',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'MX-MX-LA',
  source: 'MX',
  target: 'MX',
  airline: {
    name: 'LAN Airlines',
    country: 'Chile',
    countryCode: 'cl',
    continent: 'South America',
  },
},
{
  id: 'CG-BJ-LC',
  source: 'CG',
  target: 'BJ',
  airline: {
    name: 'Varig Log',
    country: 'Brazil',
    countryCode: 'br',
    continent: 'South America',
  },
},
{
  id: 'CG-CM-LC',
  source: 'CG',
  target: 'CM',
  airline: {
    name: 'Varig Log',
    country: 'Brazil',
    countryCode: 'br',
    continent: 'South America',
  },
},
{
  id: 'CG-CG-LC',
  source: 'CG',
  target: 'CG',
  airline: {
    name: 'Varig Log',
    country: 'Brazil',
    countryCode: 'br',
    continent: 'South America',
  },
},
{
  id: 'BJ-CG-LC',
  source: 'BJ',
  target: 'CG',
  airline: {
    name: 'Varig Log',
    country: 'Brazil',
    countryCode: 'br',
    continent: 'South America',
  },
},
{
  id: 'BJ-CM-LC',
  source: 'BJ',
  target: 'CM',
  airline: {
    name: 'Varig Log',
    country: 'Brazil',
    countryCode: 'br',
    continent: 'South America',
  },
},
{
  id: 'CM-CG-LC',
  source: 'CM',
  target: 'CG',
  airline: {
    name: 'Varig Log',
    country: 'Brazil',
    countryCode: 'br',
    continent: 'South America',
  },
},
{
  id: 'CM-BJ-LC',
  source: 'CM',
  target: 'BJ',
  airline: {
    name: 'Varig Log',
    country: 'Brazil',
    countryCode: 'br',
    continent: 'South America',
  },
},
{
  id: 'TH-LA-LF',
  source: 'TH',
  target: 'LA',
  airline: {
    name: 'FlyNordic',
    country: 'Sweden',
    countryCode: 'se',
    continent: 'Europe',
  },
},
{
  id: 'LA-LA-LF',
  source: 'LA',
  target: 'LA',
  airline: {
    name: 'FlyNordic',
    country: 'Sweden',
    countryCode: 'se',
    continent: 'Europe',
  },
},
{
  id: 'LA-TH-LF',
  source: 'LA',
  target: 'TH',
  airline: {
    name: 'FlyNordic',
    country: 'Sweden',
    countryCode: 'se',
    continent: 'Europe',
  },
},
{
  id: 'CN-CN-MF',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'Xiamen Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-TW-MF',
  source: 'CN',
  target: 'TW',
  airline: {
    name: 'Xiamen Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'TW-CN-MF',
  source: 'TW',
  target: 'CN',
  airline: {
    name: 'Xiamen Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'NL-CH-MH',
  source: 'NL',
  target: 'CH',
  airline: {
    name: 'Malaysia Airlines',
    country: 'Malaysia',
    countryCode: 'my',
    continent: 'Asia',
  },
},
{
  id: 'CN-CN-MU',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'NL-ES-MU',
  source: 'NL',
  target: 'ES',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'NL-FR-MU',
  source: 'NL',
  target: 'FR',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'NL-DK-MU',
  source: 'NL',
  target: 'DK',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'NL-IT-MU',
  source: 'NL',
  target: 'IT',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'NL-GB-MU',
  source: 'NL',
  target: 'GB',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'ES-NL-MU',
  source: 'ES',
  target: 'NL',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'TH-CN-MU',
  source: 'TH',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'IN-CN-MU',
  source: 'IN',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'FR-NL-MU',
  source: 'FR',
  target: 'NL',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'LK-CN-MU',
  source: 'LK',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'LK-MV-MU',
  source: 'LK',
  target: 'MV',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'DK-NL-MU',
  source: 'DK',
  target: 'NL',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'BD-CN-MU',
  source: 'BD',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'VN-CN-MU',
  source: 'VN',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'IT-NL-MU',
  source: 'IT',
  target: 'NL',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'HK-CN-MU',
  source: 'HK',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-TH-MU',
  source: 'CN',
  target: 'TH',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-IN-MU',
  source: 'CN',
  target: 'IN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-LK-MU',
  source: 'CN',
  target: 'LK',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-BD-MU',
  source: 'CN',
  target: 'BD',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-VN-MU',
  source: 'CN',
  target: 'VN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-HK-MU',
  source: 'CN',
  target: 'HK',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-NP-MU',
  source: 'CN',
  target: 'NP',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-MM-MU',
  source: 'CN',
  target: 'MM',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-KH-MU',
  source: 'CN',
  target: 'KH',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-LA-MU',
  source: 'CN',
  target: 'LA',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'NP-CN-MU',
  source: 'NP',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'GB-NL-MU',
  source: 'GB',
  target: 'NL',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'MV-LK-MU',
  source: 'MV',
  target: 'LK',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'MM-CN-MU',
  source: 'MM',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'KH-CN-MU',
  source: 'KH',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-TW-MU',
  source: 'CN',
  target: 'TW',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'TW-CN-MU',
  source: 'TW',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'LA-CN-MU',
  source: 'LA',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'AU-CN-MU',
  source: 'AU',
  target: 'CN',
  airline: {
    name: 'China Eastern Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'JP-JP-NH',
  source: 'JP',
  target: 'JP',
  airline: {
    name: 'All Nippon Airways',
    country: 'Japan',
    countryCode: 'jp',
    continent: 'Asia',
  },
},
{
  id: 'IN-JP-NH',
  source: 'IN',
  target: 'JP',
  airline: {
    name: 'All Nippon Airways',
    country: 'Japan',
    countryCode: 'jp',
    continent: 'Asia',
  },
},
{
  id: 'CN-JP-NH',
  source: 'CN',
  target: 'JP',
  airline: {
    name: 'All Nippon Airways',
    country: 'Japan',
    countryCode: 'jp',
    continent: 'Asia',
  },
},
{
  id: 'KR-JP-NH',
  source: 'KR',
  target: 'JP',
  airline: {
    name: 'All Nippon Airways',
    country: 'Japan',
    countryCode: 'jp',
    continent: 'Asia',
  },
},
{
  id: 'HK-JP-NH',
  source: 'HK',
  target: 'JP',
  airline: {
    name: 'All Nippon Airways',
    country: 'Japan',
    countryCode: 'jp',
    continent: 'Asia',
  },
},
{
  id: 'JP-CN-NH',
  source: 'JP',
  target: 'CN',
  airline: {
    name: 'All Nippon Airways',
    country: 'Japan',
    countryCode: 'jp',
    continent: 'Asia',
  },
},
{
  id: 'JP-HK-NH',
  source: 'JP',
  target: 'HK',
  airline: {
    name: 'All Nippon Airways',
    country: 'Japan',
    countryCode: 'jp',
    continent: 'Asia',
  },
},
{
  id: 'JP-IN-NH',
  source: 'JP',
  target: 'IN',
  airline: {
    name: 'All Nippon Airways',
    country: 'Japan',
    countryCode: 'jp',
    continent: 'Asia',
  },
},
{
  id: 'HK-MN-OM',
  source: 'HK',
  target: 'MN',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'JP-MN-OM',
  source: 'JP',
  target: 'MN',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'CN-MN-OM',
  source: 'CN',
  target: 'MN',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'RU-DE-OM',
  source: 'RU',
  target: 'DE',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'RU-MN-OM',
  source: 'RU',
  target: 'MN',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'DE-RU-OM',
  source: 'DE',
  target: 'RU',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'MN-HK-OM',
  source: 'MN',
  target: 'HK',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'MN-JP-OM',
  source: 'MN',
  target: 'JP',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'MN-CN-OM',
  source: 'MN',
  target: 'CN',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'MN-RU-OM',
  source: 'MN',
  target: 'RU',
  airline: {
    name: 'MIAT Mongolian Airlines',
    country: 'Mongolia',
    countryCode: 'mn',
    continent: 'Asia',
  },
},
{
  id: 'PE-PE-P9',
  source: 'PE',
  target: 'PE',
  airline: {
    name: 'Peruvian Airlines',
    country: 'Peru',
    countryCode: 'pe',
    continent: 'South America',
  },
},
{
  id: 'AE-PK-PK',
  source: 'AE',
  target: 'PK',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'BH-PK-PK',
  source: 'BH',
  target: 'PK',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'PK-PK-PK',
  source: 'PK',
  target: 'PK',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'IN-PK-PK',
  source: 'IN',
  target: 'PK',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'PK-AE-PK',
  source: 'PK',
  target: 'AE',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'SA-PK-PK',
  source: 'SA',
  target: 'PK',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'PK-IN-PK',
  source: 'PK',
  target: 'IN',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'PK-SA-PK',
  source: 'PK',
  target: 'SA',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'PK-BH-PK',
  source: 'PK',
  target: 'BH',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'PK-OM-PK',
  source: 'PK',
  target: 'OM',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'OM-PK-PK',
  source: 'OM',
  target: 'PK',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'IR-PK-PK',
  source: 'IR',
  target: 'PK',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'PK-IR-PK',
  source: 'PK',
  target: 'IR',
  airline: {
    name: 'Pakistan International Airlines',
    country: 'Pakistan',
    countryCode: 'pk',
    continent: 'Asia',
  },
},
{
  id: 'UA-CY-PS',
  source: 'UA',
  target: 'CY',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'AZ-UA-PS',
  source: 'AZ',
  target: 'UA',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'GR-UA-PS',
  source: 'GR',
  target: 'UA',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'UA-AZ-PS',
  source: 'UA',
  target: 'AZ',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'UA-GR-PS',
  source: 'UA',
  target: 'GR',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'UA-BY-PS',
  source: 'UA',
  target: 'BY',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'UA-ES-PS',
  source: 'UA',
  target: 'ES',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'CY-UA-PS',
  source: 'CY',
  target: 'UA',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'BY-UA-PS',
  source: 'BY',
  target: 'UA',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'ES-UA-PS',
  source: 'ES',
  target: 'UA',
  airline: {
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    countryCode: 'ua',
    continent: 'Europe',
  },
},
{
  id: 'SB-FJ-PX',
  source: 'SB',
  target: 'FJ',
  airline: {
    name: 'Air Niugini',
    country: 'Papua New Guinea',
    countryCode: 'pg',
    continent: 'Oceania',
  },
},
{
  id: 'SB-PG-PX',
  source: 'SB',
  target: 'PG',
  airline: {
    name: 'Air Niugini',
    country: 'Papua New Guinea',
    countryCode: 'pg',
    continent: 'Oceania',
  },
},
{
  id: 'PG-PG-PX',
  source: 'PG',
  target: 'PG',
  airline: {
    name: 'Air Niugini',
    country: 'Papua New Guinea',
    countryCode: 'pg',
    continent: 'Oceania',
  },
},
{
  id: 'FJ-SB-PX',
  source: 'FJ',
  target: 'SB',
  airline: {
    name: 'Air Niugini',
    country: 'Papua New Guinea',
    countryCode: 'pg',
    continent: 'Oceania',
  },
},
{
  id: 'FJ-PG-PX',
  source: 'FJ',
  target: 'PG',
  airline: {
    name: 'Air Niugini',
    country: 'Papua New Guinea',
    countryCode: 'pg',
    continent: 'Oceania',
  },
},
{
  id: 'PG-SB-PX',
  source: 'PG',
  target: 'SB',
  airline: {
    name: 'Air Niugini',
    country: 'Papua New Guinea',
    countryCode: 'pg',
    continent: 'Oceania',
  },
},
{
  id: 'PG-FJ-PX',
  source: 'PG',
  target: 'FJ',
  airline: {
    name: 'Air Niugini',
    country: 'Papua New Guinea',
    countryCode: 'pg',
    continent: 'Oceania',
  },
},
{
  id: 'CI-NG-QC',
  source: 'CI',
  target: 'NG',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'CG-CD-QC',
  source: 'CG',
  target: 'CD',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'BJ-CM-QC',
  source: 'BJ',
  target: 'CM',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'CM-CG-QC',
  source: 'CM',
  target: 'CG',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'CM-BJ-QC',
  source: 'CM',
  target: 'BJ',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'CM-CM-QC',
  source: 'CM',
  target: 'CM',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'CM-GA-QC',
  source: 'CM',
  target: 'GA',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'CM-NG-QC',
  source: 'CM',
  target: 'NG',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'CM-TD-QC',
  source: 'CM',
  target: 'TD',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'CD-CM-QC',
  source: 'CD',
  target: 'CM',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'GA-CM-QC',
  source: 'GA',
  target: 'CM',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'NG-CI-QC',
  source: 'NG',
  target: 'CI',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'NG-CM-QC',
  source: 'NG',
  target: 'CM',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'TD-CM-QC',
  source: 'TD',
  target: 'CM',
  airline: {
    name: 'Camair-co',
    country: 'Cameroon',
    countryCode: 'cm',
    continent: 'Africa',
  },
},
{
  id: 'JO-EG-RL',
  source: 'JO',
  target: 'EG',
  airline: {
    name: 'Royal Falcon',
    country: 'Jordan',
    countryCode: 'jo',
    continent: 'Asia',
  },
},
{
  id: 'EG-JO-RL',
  source: 'EG',
  target: 'JO',
  airline: {
    name: 'Royal Falcon',
    country: 'Jordan',
    countryCode: 'jo',
    continent: 'Asia',
  },
},
{
  id: 'TH-BD-RX',
  source: 'TH',
  target: 'BD',
  airline: {
    name: 'Rainbow Air Polynesia',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'BD-TH-RX',
  source: 'BD',
  target: 'TH',
  airline: {
    name: 'Rainbow Air Polynesia',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'BD-BD-RX',
  source: 'BD',
  target: 'BD',
  airline: {
    name: 'Rainbow Air Polynesia',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'BD-MY-RX',
  source: 'BD',
  target: 'MY',
  airline: {
    name: 'Rainbow Air Polynesia',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'BD-SG-RX',
  source: 'BD',
  target: 'SG',
  airline: {
    name: 'Rainbow Air Polynesia',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'MY-BD-RX',
  source: 'MY',
  target: 'BD',
  airline: {
    name: 'Rainbow Air Polynesia',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'SG-BD-RX',
  source: 'SG',
  target: 'BD',
  airline: {
    name: 'Rainbow Air Polynesia',
    country: 'United States',
    countryCode: 'us',
    continent: 'North America',
  },
},
{
  id: 'RU-RU-S7',
  source: 'RU',
  target: 'RU',
  airline: {
    name: 'S7 Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'CN-CN-SC',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'Shandong Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'IN-IN-SG',
  source: 'IN',
  target: 'IN',
  airline: {
    name: 'Spicejet',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'IN-AE-SG',
  source: 'IN',
  target: 'AE',
  airline: {
    name: 'Spicejet',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'IN-OM-SG',
  source: 'IN',
  target: 'OM',
  airline: {
    name: 'Spicejet',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'IN-AF-SG',
  source: 'IN',
  target: 'AF',
  airline: {
    name: 'Spicejet',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'IN-NP-SG',
  source: 'IN',
  target: 'NP',
  airline: {
    name: 'Spicejet',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'AE-IN-SG',
  source: 'AE',
  target: 'IN',
  airline: {
    name: 'Spicejet',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'AF-IN-SG',
  source: 'AF',
  target: 'IN',
  airline: {
    name: 'Spicejet',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'NP-IN-SG',
  source: 'NP',
  target: 'IN',
  airline: {
    name: 'Spicejet',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'OM-IN-SG',
  source: 'OM',
  target: 'IN',
  airline: {
    name: 'Spicejet',
    country: 'India',
    countryCode: 'in',
    continent: 'Asia',
  },
},
{
  id: 'NL-RU-SU',
  source: 'NL',
  target: 'RU',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'CN-CN-SU',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'CN-RU-SU',
  source: 'CN',
  target: 'RU',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'KR-RU-SU',
  source: 'KR',
  target: 'RU',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'RU-CN-SU',
  source: 'RU',
  target: 'CN',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'RU-RU-SU',
  source: 'RU',
  target: 'RU',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'RU-NL-SU',
  source: 'RU',
  target: 'NL',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'RO-RU-SU',
  source: 'RO',
  target: 'RU',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'RU-RO-SU',
  source: 'RU',
  target: 'RO',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'RU-DE-SU',
  source: 'RU',
  target: 'DE',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'DE-RU-SU',
  source: 'DE',
  target: 'RU',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'RU-KR-SU',
  source: 'RU',
  target: 'KR',
  airline: {
    name: 'Aeroflot Russian Airlines',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'RU-TJ-SZ',
  source: 'RU',
  target: 'TJ',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'KZ-TJ-SZ',
  source: 'KZ',
  target: 'TJ',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'AE-TJ-SZ',
  source: 'AE',
  target: 'TJ',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'TJ-KZ-SZ',
  source: 'TJ',
  target: 'KZ',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'TJ-RU-SZ',
  source: 'TJ',
  target: 'RU',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'TJ-AE-SZ',
  source: 'TJ',
  target: 'AE',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'TJ-DE-SZ',
  source: 'TJ',
  target: 'DE',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'TJ-TR-SZ',
  source: 'TJ',
  target: 'TR',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'TJ-CN-SZ',
  source: 'TJ',
  target: 'CN',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'DE-TJ-SZ',
  source: 'DE',
  target: 'TJ',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'TR-TJ-SZ',
  source: 'TR',
  target: 'TJ',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'CN-TJ-SZ',
  source: 'CN',
  target: 'TJ',
  airline: {
    name: 'Salzburg arrows',
    country: 'Austria',
    countryCode: 'at',
    continent: 'Europe',
  },
},
{
  id: 'CU-CA-TS',
  source: 'CU',
  target: 'CA',
  airline: {
    name: 'Air Transat',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'CA-US-TS',
  source: 'CA',
  target: 'US',
  airline: {
    name: 'Air Transat',
    country: 'Canada',
    countryCode: 'ca',
    continent: 'North America',
  },
},
{
  id: 'TH-KR-TW',
  source: 'TH',
  target: 'KR',
  airline: {
    name: 'Tway Airlines',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'KR-KR-TW',
  source: 'KR',
  target: 'KR',
  airline: {
    name: 'Tway Airlines',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'JP-KR-TW',
  source: 'JP',
  target: 'KR',
  airline: {
    name: 'Tway Airlines',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'KR-TW-TW',
  source: 'KR',
  target: 'TW',
  airline: {
    name: 'Tway Airlines',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'KR-TH-TW',
  source: 'KR',
  target: 'TH',
  airline: {
    name: 'Tway Airlines',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'KR-JP-TW',
  source: 'KR',
  target: 'JP',
  airline: {
    name: 'Tway Airlines',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'KR-CN-TW',
  source: 'KR',
  target: 'CN',
  airline: {
    name: 'Tway Airlines',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'CN-KR-TW',
  source: 'CN',
  target: 'KR',
  airline: {
    name: 'Tway Airlines',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'TW-KR-TW',
  source: 'TW',
  target: 'KR',
  airline: {
    name: 'Tway Airlines',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'US-BS-UP',
  source: 'US',
  target: 'BS',
  airline: {
    name: 'Bahamasair',
    country: 'Bahamas',
    countryCode: 'bs',
    continent: 'North America',
  },
},
{
  id: 'CU-BS-UP',
  source: 'CU',
  target: 'BS',
  airline: {
    name: 'Bahamasair',
    country: 'Bahamas',
    countryCode: 'bs',
    continent: 'North America',
  },
},
{
  id: 'US-KN-UP',
  source: 'US',
  target: 'KN',
  airline: {
    name: 'Bahamasair',
    country: 'Bahamas',
    countryCode: 'bs',
    continent: 'North America',
  },
},
{
  id: 'BS-US-UP',
  source: 'BS',
  target: 'US',
  airline: {
    name: 'Bahamasair',
    country: 'Bahamas',
    countryCode: 'bs',
    continent: 'North America',
  },
},
{
  id: 'BS-CU-UP',
  source: 'BS',
  target: 'CU',
  airline: {
    name: 'Bahamasair',
    country: 'Bahamas',
    countryCode: 'bs',
    continent: 'North America',
  },
},
{
  id: 'KN-BS-UP',
  source: 'KN',
  target: 'BS',
  airline: {
    name: 'Bahamasair',
    country: 'Bahamas',
    countryCode: 'bs',
    continent: 'North America',
  },
},
{
  id: 'ES-RO-UX',
  source: 'ES',
  target: 'RO',
  airline: {
    name: 'Air Europa',
    country: 'Spain',
    countryCode: 'es',
    continent: 'Europe',
  },
},
{
  id: 'RO-ES-UX',
  source: 'RO',
  target: 'ES',
  airline: {
    name: 'Air Europa',
    country: 'Spain',
    countryCode: 'es',
    continent: 'Europe',
  },
},
{
  id: 'RU-KG-YK',
  source: 'RU',
  target: 'KG',
  airline: {
    name: 'Cyprus Turkish Airlines',
    country: 'Turkey',
    countryCode: 'tr',
    continent: 'Asia',
  },
},
{
  id: 'KG-RU-YK',
  source: 'KG',
  target: 'RU',
  airline: {
    name: 'Cyprus Turkish Airlines',
    country: 'Turkey',
    countryCode: 'tr',
    continent: 'Asia',
  },
},
{
  id: 'UA-UA-Z6',
  source: 'UA',
  target: 'UA',
  airline: {
    name: 'ZABAIKAL AIRLINES',
    country: 'Russia',
    countryCode: 'ru',
    continent: 'Europe',
  },
},
{
  id: 'KR-KR-ZE',
  source: 'KR',
  target: 'KR',
  airline: {
    name: 'Eastar Jet',
    country: 'South Korea',
    countryCode: 'kr',
    continent: 'Asia',
  },
},
{
  id: 'ET-CN-ZH',
  source: 'ET',
  target: 'CN',
  airline: {
    name: 'Shenzhen Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-CN-ZH',
  source: 'CN',
  target: 'CN',
  airline: {
    name: 'Shenzhen Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
{
  id: 'CN-ET-ZH',
  source: 'CN',
  target: 'ET',
  airline: {
    name: 'Shenzhen Airlines',
    country: 'China',
    countryCode: 'cn',
    continent: 'Asia',
  },
},
]

export const groups = ['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America']
export const data = { nodes, links }
